services:
  dev-db:
    image: postgres:latest
    environment:
      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - 5434:5432
    networks:
      - Mustafa

networks:
  Mustafa: